/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-reset-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyResetCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/points/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["redeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRecurringProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savings/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sepa/precios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulta EN VIVO contra el dataset SEPA (lento: descarga y parsea el zip; solo ADMIN)
         * @description Resuelve el recurso más reciente vía API CKAN (o el día indicado), lo cachea en disco y devuelve los precios normalizados, filtrados y paginados. La primera llamada del día puede tardar varios minutos.
         */
        get: operations["getPrecios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sepa/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulta el snapshot en DB (rápido; agregado por EAN)
         * @description Busca en la tabla sepa_producto cargada por la sincronización semanal. Precio mínimo/promedio/máximo entre todos los comercios y sucursales. Ordenado por cantidad de ofertas. Incluye imagenUrl si ya fue resuelta; si viene null, el EAN queda encolado para resolverse en background.
         */
        get: operations["getProductos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sepa/productos/{ean}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle de un producto por EAN, pensado para el escaneo de código de barras
         * @description Devuelve el agregado de precios, el desglose por comercio (del más barato al más caro) y la imagen. Responde 200 siempre: si el EAN no está en el snapshot, viene encontrado=false y se intenta completar nombre e imagen desde los proveedores externos, con un tope de tiempo corto.
         */
        get: operations["getProductoPorEan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sepa/productos/{ean}/sucursales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dónde está más barato un producto cerca de una ubicación
         * @description De cada cadena, la sucursal más barata dentro del radio (por defecto 5 km, máximo 30), con su dirección y coordenadas para navegar hasta ella. Los precios son por sucursal, no el mínimo de la cadena en todo el país. Responde 200 con la lista vacía si no hay sucursales con precio en el radio.
         */
        get: operations["getSucursalesCercanas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sepa/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispara la sincronización del snapshot en DB (requiere rol ADMIN)
         * @description Responde 202 al instante y sigue en background. Seguir el progreso con GET /sepa/sync/estado.
         */
        post: operations["sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sepa/sync/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de la sincronización en curso o de la última ejecutada (solo ADMIN) */
        get: operations["syncEstado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFavorites"];
        put: operations["updateFavorites"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNearby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTicket"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlternativeOffer: {
            brand: string | null;
            discountPct: number | null;
            listPrice: number | null;
            price: number;
            productName: string;
            retailerName: string;
        };
        AuthResponse: {
            token: string;
            user: components["schemas"]["UserProfileResponse"];
        };
        BestOffer: {
            discountPct: number | null;
            imageUrl: string | null;
            listPrice: number | null;
            price: number;
            productName: string | null;
            promoLabel: string | null;
            promoLabels: string[];
            promoUnitPrice: number | null;
            /** Format: int32 */
            requiredQuantity: number | null;
            retailerName: string;
        };
        CampaignOffer: {
            activeTo: string | null;
            discountPercentages: number[];
            imageUrl: string | null;
            legalText: string | null;
            /** @enum {string|null} */
            mechanic: "second_unit" | "3x2" | "2x1" | "percentage_off" | null;
            offerId: string | null;
            percentagesUnverified: boolean;
            province: string | null;
            retailerName: string;
        };
        CategorySavings: {
            category: string | null;
            /** Format: int64 */
            itemCount: number;
            totalDiscounts: number;
        };
        ChangePasswordRequest: {
            currentPassword?: string;
            newPassword?: string;
        };
        ComercioPrecioResponse: {
            bandera: string | null;
            /** Format: int32 */
            cantidadSucursales: number;
            comercioId: string | null;
            precioMaximo: number | null;
            precioMinimo: number | null;
            razonSocial: string | null;
        };
        FavoriteStoresResponse: {
            chainSlugs: string[];
            /** Format: int32 */
            radiusKm: number;
        };
        ForgotPasswordRequest: {
            email?: string;
        };
        LoginRequest: {
            email?: string;
            password?: string;
        };
        Offer: {
            activeTo: string | null;
            brand: string | null;
            category: string | null;
            discountPct: number | null;
            discountPercentages: number[] | null;
            headline: string;
            id: string;
            imageUrl: string | null;
            /** @enum {string} */
            kind: "catalog" | "campaign";
            legalText: string | null;
            listPrice: number | null;
            /** @enum {string|null} */
            mechanic: "second_unit" | "3x2" | "2x1" | "percentage_off" | null;
            percentagesUnverified: boolean;
            price: number | null;
            productName: string | null;
            province: string | null;
            retailerName: string | null;
            retailerSlug: string | null;
            url: string | null;
        };
        OfferFeedResponse: {
            items: components["schemas"]["Offer"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageSepaProductoResponse: {
            content?: components["schemas"]["SepaProductoResponse"][];
            empty?: boolean;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            size?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            paged?: boolean;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
        };
        PointsBalanceResponse: {
            /** Format: int32 */
            balance: number;
            referralCode: string | null;
        };
        PointsHistoryEntryResponse: {
            /** Format: date-time */
            createdAt: string;
            description: string;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            points: number;
            /** @enum {string} */
            reason: "REFERRAL_SIGNUP" | "REFERRAL_ACTIVATED" | "REFERRAL_RETAINED" | "REDEEM";
        };
        ProductSavings: {
            barcode: string | null;
            category: string | null;
            description: string;
            /** Format: int64 */
            purchaseCount: number;
            totalDiscounts: number;
        };
        PromoMechanic: {
            imageUrl: string | null;
            listPrice: number | null;
            productName: string | null;
            promoLabels: string[];
            promoUnitPrice: number | null;
            /** Format: int32 */
            requiredQuantity: number | null;
            retailerName: string;
            unitPrice: number | null;
        };
        RecurringProductResponse: {
            alternativeOffers: components["schemas"]["AlternativeOffer"][];
            barcode: string | null;
            bestOffer: components["schemas"]["BestOffer"] | null;
            campaignOffers: components["schemas"]["CampaignOffer"][];
            category: string | null;
            description: string;
            inReferenceTicket: boolean;
            /** Format: date-time */
            lastPaidAt: string | null;
            lastPaidPrice: number | null;
            promoMechanics: components["schemas"]["PromoMechanic"][];
            /** Format: int64 */
            purchaseCount: number;
            /** Format: int64 */
            ticketCount: number;
            totalDiscounts: number;
        };
        RedeemRequest: {
            /** Format: int32 */
            points?: number;
            rewardId?: string;
        };
        RegisterPushTokenRequest: {
            platform?: string;
            token?: string;
        };
        RegisterRequest: {
            email?: string;
            name?: string;
            password?: string;
            referralCode?: string;
        };
        ResetPasswordRequest: {
            code?: string;
            email?: string;
            newPassword?: string;
        };
        SavingsReportResponse: {
            byCategory: components["schemas"]["CategorySavings"][];
            byStore: components["schemas"]["StoreSavings"][];
            summary: components["schemas"]["Summary"];
            timeline: components["schemas"]["TimelineSavings"][];
            topProducts: components["schemas"]["ProductSavings"][];
        };
        SepaPrecioResponse: {
            bandera: string | null;
            banderaId: string | null;
            cantidadPresentacion: string | null;
            comercioCuit: string | null;
            comercioId: string | null;
            comercioRazonSocial: string | null;
            descripcion: string | null;
            ean: string;
            leyendaPromo1: string | null;
            leyendaPromo2: string | null;
            marca: string | null;
            precioLista: number | null;
            precioPromo1: number | null;
            precioPromo2: number | null;
            precioReferencia: number | null;
            productoId: string | null;
            sucursalId: string | null;
            unidadMedidaPresentacion: string | null;
            unidadMedidaReferencia: string | null;
        };
        SepaPreciosPageResponse: {
            data: components["schemas"]["SepaPrecioResponse"][];
            dia: string;
            fecha: string;
            /** Format: int32 */
            page: number;
            recursoUrl: string;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElementos: number;
            /** Format: int64 */
            totalPaginas: number;
        };
        SepaProductoDetalleResponse: {
            /** Format: int32 */
            cantidadOfertas: number;
            comercios: components["schemas"]["ComercioPrecioResponse"][];
            descripcion: string | null;
            ean: string;
            encontrado: boolean;
            /** Format: date */
            fechaDataset: string | null;
            fuenteDatos: string;
            imagenUrl: string | null;
            marca: string | null;
            precioMaximo: number | null;
            precioMinimo: number | null;
            precioPromedio: number | null;
            sinPrecios: boolean;
        };
        SepaProductoResponse: {
            /** Format: int32 */
            cantidadOfertas: number;
            descripcion: string | null;
            ean: string;
            /** Format: date */
            fechaDataset: string | null;
            /** Format: int64 */
            id: number;
            imagenUrl: string | null;
            marca: string | null;
            precioMaximo: number | null;
            precioMinimo: number | null;
            precioPromedio: number | null;
        };
        SepaSucursalesCercanasResponse: {
            ean: string;
            /** Format: date */
            fechaDataset: string | null;
            /** Format: double */
            radioKm: number;
            sucursales: components["schemas"]["SucursalPrecioResponse"][];
        };
        SepaSyncEstadoResponse: {
            dia: string | null;
            /** Format: int64 */
            duracionSegundos: number;
            error: string | null;
            /** @enum {string} */
            estado: "IDLE" | "EN_CURSO" | "OK" | "ERROR";
            fechaDataset: string | null;
            /** Format: int64 */
            filasProcesadas: number;
            fin: string | null;
            inicio: string | null;
            /** Format: int64 */
            productosGuardados: number;
            /** Format: int64 */
            productosInsertados: number;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        StoreSavings: {
            storeName: string | null;
            /** Format: int64 */
            ticketCount: number;
            totalDiscounts: number;
        };
        SucursalPrecioResponse: {
            bandera: string | null;
            banderaId: string | null;
            comercioId: string | null;
            direccion: string | null;
            /** Format: double */
            distanciaKm: number;
            /** Format: double */
            latitud: number;
            localidad: string | null;
            /** Format: double */
            longitud: number;
            nombre: string | null;
            precio: number;
            provincia: string | null;
            /** Format: int64 */
            sucursalId: number;
            tipo: string | null;
        };
        Summary: {
            averageSavings: number;
            /** Format: int32 */
            ticketCount: number;
            totalSavings: number;
            totalSpent: number;
        };
        TicketItemResponse: {
            barcode: string | null;
            category: string | null;
            description: string;
            discountAmount: number | null;
            discountDescription: string | null;
            /** Format: int64 */
            id: number;
            originalPrice: number | null;
            quantity: number;
            rawDescription: string | null;
            subtotal: number | null;
            unitPrice: number;
        };
        TicketItemUpdate: {
            description?: string;
            discountAmount?: number;
            /** Format: int64 */
            id?: number;
            originalPrice?: number;
            quantity?: number;
            unitPrice?: number;
        };
        TicketResponse: {
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            id: number;
            items: components["schemas"]["TicketItemResponse"][];
            reviewed: boolean;
            /** @enum {string} */
            status: "PENDING" | "PROCESSED" | "FAILED";
            storeName: string | null;
            subtotal: number | null;
            ticketId: string | null;
            total: number | null;
            totalDiscounts: number | null;
        };
        TimelineSavings: {
            period: string;
            /** Format: int32 */
            ticketCount: number;
            totalDiscounts: number;
        };
        UpdateFavoriteStoresRequest: {
            chainSlugs?: string[];
            /** Format: int32 */
            radiusKm?: number;
        };
        UpdateProfileRequest: {
            address?: string;
            alternativeBrandsEnabled?: boolean;
            currentPassword?: string;
            email?: string;
            name?: string;
            offersPushEnabled?: boolean;
            profilePicture?: string;
        };
        UpdateTicketRequest: {
            items?: components["schemas"]["TicketItemUpdate"][];
            storeName?: string;
        };
        UserProfileResponse: {
            address: string | null;
            alternativeBrandsEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
            email: string;
            /** Format: int64 */
            id: number;
            name: string;
            offersPushEnabled: boolean;
            /** Format: int32 */
            points: number;
            profilePicture: string | null;
            referralCode: string | null;
        };
        VerifyResetCodeRequest: {
            code?: string;
            email?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    register_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyResetCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyResetCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOffers: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                province?: string;
                chains?: string;
                categories?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OfferFeedResponse"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PointsHistoryEntryResponse"][];
                };
            };
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PointsBalanceResponse"];
                };
            };
        };
    };
    redeem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PointsBalanceResponse"];
                };
            };
        };
    };
    getRecurringProducts: {
        parameters: {
            query?: {
                ticketId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecurringProductResponse"][];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPushTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReport: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SavingsReportResponse"];
                };
            };
        };
    };
    getPrecios: {
        parameters: {
            query?: {
                /** @description Día del recurso (lunes..viernes). Si se omite, usa el más reciente */
                dia?: string;
                /** @description Filtro por comercio: razón social, bandera, CUIT o id_comercio */
                comercio?: string;
                /** @description Filtro por descripción o marca del producto (contiene, sin acentos) */
                producto?: string;
                /** @description Filtro por código EAN exacto */
                ean?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SepaPreciosPageResponse"];
                };
            };
        };
    };
    getProductos: {
        parameters: {
            query?: {
                /** @description Búsqueda por palabras de la descripción o marca */
                q?: string;
                /** @description Código EAN exacto */
                ean?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageSepaProductoResponse"];
                };
            };
        };
    };
    getProductoPorEan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ean: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SepaProductoDetalleResponse"];
                };
            };
        };
    };
    getSucursalesCercanas: {
        parameters: {
            query: {
                /** @description Latitud del punto de búsqueda */
                lat: number;
                /** @description Longitud del punto de búsqueda */
                lng: number;
                /** @description Radio en km (1 a 30) */
                radiusKm?: number;
            };
            header?: never;
            path: {
                ean: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SepaSucursalesCercanasResponse"];
                };
            };
        };
    };
    sync: {
        parameters: {
            query?: {
                dia?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SepaSyncEstadoResponse"];
                };
            };
        };
    };
    syncEstado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SepaSyncEstadoResponse"];
                };
            };
        };
    };
    getChains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    }[];
                };
            };
        };
    };
    getFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FavoriteStoresResponse"];
                };
            };
        };
    };
    updateFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFavoriteStoresRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FavoriteStoresResponse"];
                };
            };
        };
    };
    getNearby: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radiusKm?: number;
                onlyFavorites?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    }[];
                };
            };
        };
    };
    getMyTickets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"][];
                };
            };
        };
    };
    scan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    file: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"];
                };
            };
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TicketResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
}
